### ISSUE TITLE
Semantic of `MaxHostQPS` and `MaxDepth`

### ISSUE THREAD

**Issue by amirouche** [cocrawler/cocrawler#10]
### `MaxHostQPS`

It seems it is the maximum the number of requests that can be made per second against a given host. How does it relate to `crawl-delay` in robots.txt?

### `MaxDepth`

Does this option limit the crawl depth inside the seed? Or it does control the overall depth, possibly in domains outside the seed?

Does cocrawl crawl domains that are not in the seed?

**Comment by wumpus** [comment]
cocrawler ignores `crawl-delay` in robots.txt. (Most wide-ranging webcrawlers do.)

MaxDepth is distance from the seed. You can pick from a variety of crawl policies: SeedsDomain, SeedsHostname, SeedsPrefix, OnlySeeds, AllDomains. See `url_allowed.py`

**Comment by amirouche** [comment]
Thanks :+1:
